name: test_env_xgcm
dependencies:
  - python=3.6
  - xarray
  - dask
  - numpy
  # no numba to test optional dependency
  - pytest
  - future
  - pip
  - black
  - pip:
    - docrep<=0.2.7
    - codecov
    - pytest-cov
    - pytest-xdist

